// Command p02-verify validates the checked-in P02 oracle and fixture evidence.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
)

const (
	fixtureDirectory = "testdata/p02"
	evidencePath     = "docs/p02/evidence.json"
	oracleSHA256     = "8fe803ee1a5226f1ee1025ce891e6cf8dfa372e82a76c9b41bfa1d8efe6a0ae4"
	dockerfileSHA256 = "d892591e5d2adaeada139da1f70bce8a636bc4cb2972fa3ae33b7c7e9fd68af0"
	generatorTool    = "source-derived independent C++/OpenSSL oracle"
	generatorVersion = "Ceph 20.2.0 contract"
	bannerLicense    = "LGPL-2.1-or-later"
	compositeLicense = "(LGPL-2.1-or-later AND BSD-3-Clause)"
)

var (
	bannerPaths = []string{"src/include/msgr.h"}
	crcPaths    = []string{"src/include/msgr.h", "src/include/crc32c.h", "src/common/sctp_crc32.c", "src/msg/async/frames_v2.h", "src/msg/async/frames_v2.cc"}
	securePaths = []string{"src/include/msgr.h", "src/include/crc32c.h", "src/common/sctp_crc32.c", "src/msg/async/frames_v2.h", "src/msg/async/frames_v2.cc", "src/msg/async/crypto_onwire.h", "src/msg/async/crypto_onwire.cc"}
)

type fixtureExpectation struct {
	hash           string
	paths          []string
	license        string
	redistribution string
}

func expectedFixtures() map[string]fixtureExpectation {
	return map[string]fixtureExpectation{
		"banner-rev1.bin":         {hash: "6819c56d3d3d3ccaa0545a80d55aaa8088d88e9f849113cdafa58feb298cfcca", paths: bannerPaths, license: bannerLicense, redistribution: "generated bytes; retain LGPL-2.1-or-later notices"},
		"crc-four-segment.bin":    {hash: "b922bf62be1b19706c6fa26b63c9e8e6ddd9efdc3bec6705712d20f9d9e05929", paths: crcPaths, license: compositeLicense, redistribution: "generated bytes; retain LGPL-2.1-or-later and BSD-3-Clause notices"},
		"crc-one-segment.bin":     {hash: "beb6e6b846d5b2e6f544addb9bacfe92086ea1a9001aec88e61dcacfbd918389", paths: crcPaths, license: compositeLicense, redistribution: "generated bytes; retain LGPL-2.1-or-later and BSD-3-Clause notices"},
		"secure-multi-record.bin": {hash: "ef4278163cad9ef06c2dba23e4e1b1db11be4731445c4af23ac91cc0f07de469", paths: securePaths, license: compositeLicense, redistribution: "generated bytes; retain LGPL-2.1-or-later and BSD-3-Clause notices"},
		"secure-one-segment.bin":  {hash: "950b81ca9889ad23534f12c7772dec5d8cce575f63de4df92ca3850ff190de5f", paths: securePaths, license: compositeLicense, redistribution: "generated bytes; retain LGPL-2.1-or-later and BSD-3-Clause notices"},
	}
}

type evidencePins struct {
	repository string
	commit     string
	image      string
}

type manifest struct {
	SchemaVersion int       `json:"schema_version"`
	Fixture       string    `json:"fixture"`
	SHA256        string    `json:"sha256"`
	Kind          string    `json:"kind"`
	Source        source    `json:"source"`
	Generator     generator `json:"generator"`
	Secrets       secrets   `json:"secrets"`
	License       license   `json:"license"`
}

type source struct {
	Repository string   `json:"repository"`
	Commit     string   `json:"commit"`
	Paths      []string `json:"paths"`
}

type generator struct {
	Tool    string   `json:"tool"`
	Version string   `json:"version"`
	Command []string `json:"command"`
	Image   string   `json:"image"`
}

type secrets struct {
	ContainsSecrets bool `json:"contains_secrets"`
	SyntheticOnly   bool `json:"synthetic_only"`
}

type license struct {
	UpstreamExpression string `json:"upstream_expression"`
	Redistribution     string `json:"redistribution"`
}

type evidence struct {
	SchemaVersion      int               `json:"schema_version"`
	Status             string            `json:"status"`
	Source             evidenceSource    `json:"source"`
	LocalToolchain     localToolchain    `json:"local_toolchain"`
	Commands           []commandResult   `json:"commands"`
	Fixtures           map[string]string `json:"fixtures"`
	DockerReproduction reproduction      `json:"docker_reproduction"`
	UpstreamOracle     upstreamOracle    `json:"upstream_oracle"`
}

type evidenceSource struct {
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	Commit     string `json:"commit"`
}

type localToolchain struct {
	Compiler string `json:"compiler"`
	OpenSSL  string `json:"openssl"`
}

type commandResult struct {
	Command string `json:"command"`
	Result  string `json:"result"`
}

type reproduction struct {
	Command string `json:"command"`
	Result  string `json:"result"`
	Reason  string `json:"reason"`
}

type upstreamOracle struct {
	Kind   string `json:"kind"`
	Result string `json:"result"`
}

func main() {
	pins := loadEvidence()
	checkP02Evidence(pins, expectedFixtures())
	checkHash("integration/p02/oracle.cc", oracleSHA256)
	checkHash("integration/p02/Dockerfile", dockerfileSHA256)
	checkExecutable("integration/p02/reproduce.sh")

	expected := expectedFixtures()
	entries, err := os.ReadDir(fixtureDirectory)
	must(err)
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			fatalf("unexpected P02 fixture directory %s", entry.Name())
		}
		names = append(names, entry.Name())
	}
	must(validateArtifactNames(names, expected))
	for name, expectation := range expected {
		checkFixture(name, expectation, pins)
	}
	fmt.Println("P02 verification passed")
}

func validateArtifactNames(names []string, expected map[string]fixtureExpectation) error {
	wantFiles := make(map[string]bool, len(expected)*2)
	for name := range expected {
		wantFiles[name] = true
		wantFiles[name+".json"] = true
	}
	for _, name := range names {
		if !wantFiles[name] {
			return fmt.Errorf("unexpected P02 fixture artifact %s", name)
		}
		delete(wantFiles, name)
	}
	if len(wantFiles) != 0 {
		return fmt.Errorf("missing P02 fixture artifacts: %v", wantFiles)
	}
	return nil
}

func loadEvidence() evidencePins {
	var value struct {
		Ceph struct {
			Repository     string `json:"repository"`
			SourceBaseline struct {
				Commit string `json:"commit"`
			} `json:"source_baseline"`
		} `json:"ceph"`
		Images struct {
			Qualification struct {
				Reference string `json:"reference"`
			} `json:"qualification"`
		} `json:"images"`
	}
	data, err := os.ReadFile("docs/p00/evidence.json")
	must(err)
	must(json.Unmarshal(data, &value))
	if value.Ceph.Repository == "" || value.Ceph.SourceBaseline.Commit == "" || value.Images.Qualification.Reference == "" {
		fatalf("P00 evidence lacks P02 pins")
	}
	return evidencePins{repository: value.Ceph.Repository, commit: value.Ceph.SourceBaseline.Commit, image: value.Images.Qualification.Reference}
}

func checkHash(path, want string) {
	data, err := os.ReadFile(path)
	must(err)
	digest := sha256.Sum256(data)
	if got := hex.EncodeToString(digest[:]); got != want {
		fatalf("%s hash is %s, want %s", path, got, want)
	}
}

func checkExecutable(path string) {
	info, err := os.Stat(path)
	must(err)
	if !info.Mode().IsRegular() || info.Mode().Perm()&0111 == 0 {
		fatalf("%s must be a regular executable file", path)
	}
}

func checkFixture(name string, want fixtureExpectation, pins evidencePins) {
	fixturePath := filepath.Join(fixtureDirectory, name)
	data, err := os.ReadFile(fixturePath)
	must(err)
	digest := sha256.Sum256(data)
	actualHash := hex.EncodeToString(digest[:])
	if actualHash != want.hash {
		fatalf("fixture %s hash is %s, want %s", name, actualHash, want.hash)
	}

	manifestPath := fixturePath + ".json"
	manifestData, err := os.ReadFile(manifestPath)
	must(err)
	must(validateManifestDocument(manifestData))
	var value manifest
	decodeStrict(manifestPath, &value)
	if value.SchemaVersion != 1 || value.Fixture != name || value.SHA256 != want.hash || value.Kind != "native-oracle" {
		fatalf("fixture %s identity or hash metadata is invalid", name)
	}
	if value.Source.Repository != pins.repository || value.Source.Commit != pins.commit || !slices.Equal(value.Source.Paths, want.paths) {
		fatalf("fixture %s source provenance is not pinned", name)
	}
	wantCommand := []string{"./integration/p02/reproduce.sh"}
	if value.Generator.Tool != generatorTool || value.Generator.Version != generatorVersion || value.Generator.Image != pins.image || !slices.Equal(value.Generator.Command, wantCommand) {
		fatalf("fixture %s generator is not pinned", name)
	}
	if value.Secrets.ContainsSecrets || !value.Secrets.SyntheticOnly {
		fatalf("fixture %s is not marked synthetic and secret-free", name)
	}
	if value.License.UpstreamExpression != want.license || value.License.Redistribution != want.redistribution {
		fatalf("fixture %s has incorrect license or redistribution metadata", name)
	}
}

func checkP02Evidence(pins evidencePins, fixtures map[string]fixtureExpectation) {
	data, err := os.ReadFile(evidencePath)
	must(err)
	must(validateEvidenceDocument(data))
	var value evidence
	decodeStrict(evidencePath, &value)
	if value.SchemaVersion != 1 || value.Status != "incomplete/pending-upstream-oracle" {
		fatalf("P02 evidence status is invalid")
	}
	if value.Source.Repository != pins.repository || value.Source.Tag != "v20.2.0" || value.Source.Commit != pins.commit {
		fatalf("P02 evidence source is not pinned")
	}
	if value.LocalToolchain.Compiler != "Apple clang 21" || value.LocalToolchain.OpenSSL != "OpenSSL 3.6.4" {
		fatalf("P02 local toolchain evidence is invalid")
	}
	wantCommands := []commandResult{
		{Command: "gofmt -w tools/p02-verify/main.go tools/p02-verify/main_test.go", Result: "passed"},
		{Command: "go test ./tools/p02-verify ./internal/msgr", Result: "passed"},
		{Command: "CGO_ENABLED=0 go test ./...", Result: "passed"},
		{Command: "go run ./tools/p02-verify", Result: "passed"},
		{Command: "make unit-p02 differential-p02 integration-p02", Result: "passed"},
		{Command: "git diff --check", Result: "passed"},
	}
	if !slices.Equal(value.Commands, wantCommands) {
		fatalf("P02 evidence commands or results are invalid")
	}
	if len(value.Fixtures) != len(fixtures) {
		fatalf("P02 evidence fixture set is incomplete")
	}
	for name, fixture := range fixtures {
		if value.Fixtures[name] != fixture.hash {
			fatalf("P02 evidence hash for %s is invalid", name)
		}
	}
	if value.DockerReproduction.Command != "make reproduce-p02" || value.DockerReproduction.Result != "canceled" || value.DockerReproduction.Reason != "pinned image package download/build canceled; openssl-devel NEVRA and RPM checksum not recorded" {
		fatalf("P02 Docker reproduction evidence is invalid")
	}
	if value.UpstreamOracle.Kind != "Ceph FrameAssembler" || value.UpstreamOracle.Result != "pending" {
		fatalf("P02 upstream oracle gate is invalid")
	}
}

func validateEvidenceDocument(data []byte) error {
	var typed evidence
	if err := decodeDocument(data, &typed); err != nil {
		return err
	}
	var value map[string]any
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	checks := []struct {
		value map[string]any
		keys  []string
	}{{value, []string{"schema_version", "status", "source", "local_toolchain", "commands", "fixtures", "docker_reproduction", "upstream_oracle"}}}
	for _, nested := range []struct {
		key  string
		keys []string
	}{
		{"source", []string{"repository", "tag", "commit"}},
		{"local_toolchain", []string{"compiler", "openssl"}},
		{"docker_reproduction", []string{"command", "result", "reason"}},
		{"upstream_oracle", []string{"kind", "result"}},
	} {
		object, err := object(value, nested.key)
		if err != nil {
			return err
		}
		checks = append(checks, struct {
			value map[string]any
			keys  []string
		}{object, nested.keys})
	}
	for _, check := range checks {
		if err := requireKeys(check.value, check.keys...); err != nil {
			return err
		}
	}
	commands, ok := value["commands"].([]any)
	if !ok || len(commands) == 0 {
		return errors.New("evidence commands must not be empty")
	}
	for index, raw := range commands {
		command, ok := raw.(map[string]any)
		if !ok {
			return fmt.Errorf("evidence command %d must be an object", index)
		}
		if err := requireKeys(command, "command", "result"); err != nil {
			return fmt.Errorf("evidence command %d: %w", index, err)
		}
	}
	return nil
}

func validateManifestDocument(data []byte) error {
	var typed manifest
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&typed); err != nil {
		return err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return errors.New("manifest contains multiple JSON values")
		}
		return err
	}
	var value map[string]any
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	checks := []struct {
		value map[string]any
		keys  []string
	}{{value, []string{"schema_version", "fixture", "sha256", "kind", "source", "generator", "secrets", "license"}}}
	for _, nested := range []struct {
		key  string
		keys []string
	}{
		{"source", []string{"repository", "commit", "paths"}},
		{"generator", []string{"tool", "version", "command", "image"}},
		{"secrets", []string{"contains_secrets", "synthetic_only"}},
		{"license", []string{"upstream_expression", "redistribution"}},
	} {
		object, err := object(value, nested.key)
		if err != nil {
			return err
		}
		checks = append(checks, struct {
			value map[string]any
			keys  []string
		}{object, nested.keys})
	}
	for _, check := range checks {
		if err := requireKeys(check.value, check.keys...); err != nil {
			return err
		}
	}
	return nil
}

func object(value map[string]any, key string) (map[string]any, error) {
	object, ok := value[key].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("field %s must be an object", key)
	}
	return object, nil
}

func requireKeys(value map[string]any, keys ...string) error {
	for _, key := range keys {
		if _, ok := value[key]; !ok {
			return fmt.Errorf("manifest lacks required field %s", key)
		}
	}
	return nil
}

func decodeStrict(path string, value any) {
	data, err := os.ReadFile(path)
	must(err)
	must(decodeDocument(data, value))
}

func decodeDocument(data []byte, value any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(value); err != nil {
		return err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return errors.New("document contains multiple JSON values")
		}
		return err
	}
	return nil
}

func must(err error) {
	if err != nil {
		fatalf("%v", err)
	}
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "p02-verify: "+format+"\n", arguments...)
	os.Exit(1)
}
